name: Performance Tests

on: workflow_dispatch

concurrency: performance-tests

jobs:
    performance-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Build
              run: |
                  cd performance-tests
                  npm install
                  npm run build

            - name: Run Performance Tests
              uses: grafana/k6-action@v0.3.0
              with:
                  filename: performance-tests/build/hello-world.js
                  flags: --include-system-env-vars
                  cloud: true
                  token: ${{ secrets.K6_CLOUD_API_TOKEN }}
              env:
                  APP_HOST: ${{ vars.APP_HOST }}
                  APP_AUTH_BASIC_USERNAME: ${{ secrets.APP_AUTH_BASIC_USERNAME }}
                  APP_AUTH_BASIC_PASSWORD: ${{ vars.APP_AUTH_BASIC_PASSWORD }}
